### ISSUE TITLE
Download list omits some items since v2.048

### ISSUE THREAD

**Issue by Hyenard** [RePod/psdle#20] opened 2015-06-05 23:24 UTC
Hi, i currently have 3398 entries in my download list (3392 are gaming-related stuff, 6 are movie trailers) however the list generated by PSDLE tells me that i have 3396 (3395 without "Catalog" enabled, and the third missing item is "DYNASTY WARRIORS 8 Empires Free Alliances Version" for PS3) out of 3398 items.

I don't know about the other missing items. I'm using the IT store.

**Comment by RePod** [comment] 2015-06-06 08:17
[Here's a list of commits that update the Userscript.](//github.com/RePod/psdle/commits/gh-pages/psdle.user.js)

A few: [v2.046](//raw.githubusercontent.com/RePod/psdle/aa6a30195e516141b023a5cb0cc793ead1e2e6c8/psdle.user.js) (previous), [v2.041](//raw.githubusercontent.com/RePod/psdle/10e6adba55f2fb55bfdb6729831ae7aecf76d925/psdle.user.js), [v2.039](//raw.githubusercontent.com/RePod/psdle/965bbdbfee27305f55872bc8a1212fbc828da2ee/psdle.user.js).

Is there a difference between:
- Earlier versions and 2.048?
- The Userscript and a non-Userscript version *(Direct/Bookmarklet/Chrome Extension)*?

I'm not seeing anything between updates that would result in this happening.

**Comment by Hyenard** [comment] 2015-06-06 09:27
It's still showing less items with v2.046 at least.

**Comment by RePod** [comment] 2015-06-06 09:43
While viewing the store page: 
- Open the browser console (Firefox: Ctrl+Shift+K, Chrome: Ctrl+Shift+J)
- Paste the following code and submit
- Reply with results

````javascript
var a = gEntitlementManager.getAllEntitlements(), bad=0, valid=0, w=0;
$.each(a, function(i,o){
    if ((o.VUData) || (o.drm_def && o.drm_def.contentType == "TV")) { bad++ }
    else if (o.drm_def || o.entitlement_attributes) { valid++ }
    else { w++ }
})
console.log(a.length,valid,w,bad)
````

This bit of code loops through the download list similar to how PSDLE does and uses the same content checks (but logs them).

**Comment by Hyenard** [comment] 2015-06-06 09:53
All i'm getting is this: 

undefined
3569 3398 171 0

**Comment by Hyenard** [comment] 2015-06-08 12:43
Any news? Also why sometimes when i start the script, all i get is 0/0 results?

**Comment by RePod** [comment] 2015-06-08 17:34
>Any news?

Been busy, will get to it eventually™.

>Also why sometimes when i start the script, all i get is 0/0 results?

This is an intermittent issue. If I had to guess the Entitlements are loaded for whatever reason (store side), I can't do much about this. Refreshing the page seems to work.

>ps: i swear the issue with the omitted items already happened in the past but was fixed...

In my other reply I gave a list of Userscript updates. The most recent ones (within the past 3 months) haven't done anything tot the table or download list generation so I don't have a good starting place to look.

**Comment by Hyenard** [comment] 2015-06-08 17:42
No, the problems happens with Catalog enabled AND disabled. When it's enabled, i get 2 omitted results, when it's not, it's 3, and it includes that DW8 game.

Are you sure the results i posted 2 days ago are enough? It's just a bunch of random numbers for me.

**Comment by RePod** [comment] 2015-06-08 17:52
>No, the problems happens with Catalog enabled AND disabled.

Whoops.

>Are you sure the results i posted 2 days ago are enough? It's just a bunch of random numbers for me.

In order, the numbers `3569 3398 171 0` are:

- The total amount of items on your Entitlements list (store thing).
- The total amount of valid game content from your Entitlements list (validated and cached by PSDLE).
- The total amount of invalid/non-game content from your Entitlements list, such as PS+ subscriptions  (discarded by PSDLE).
- The total amount of irrelevant content, such as video content which itself is weird to detect (discarded by PSDLE)

You originally posted you were getting 3398 results (including omissions) and that snippet returned `3569 3398 171 0`. The 3398 here is the amount of valid items PSDLE sees, add that to the 171 other items to get the total: 3569. This means the snippet (and by extension, PSDLE) is seeing and processing everything on the Entitlements list as it should.

After the relevant items on the Entitlements list are cached by PSDLE it then generates the table with the available filters (system, category if Catalog is enabled) *which are all enabled by default*. The primary reason an item wouldn't display is if for some reason it failed to match the enabled systems or categories enabled.

**Comment by Hyenard** [comment] 2015-06-08 18:04
3398 is not the number shown in the download list page. The actual number is 3392, the other 6 are movie trailers.

**Comment by RePod** [comment] 2015-06-08 18:04
I made a small modification to assist in debugging this issue.

Please execute [this version](//gist.githubusercontent.com/RePod/a96eca1e48c1c97a2e47/raw/a15db8bfb5e7ce126c80feaf3147c7cd20803678/gistfile1.txt) with the Userscript disabled.

To use (same as the previous snippet):

- Open the browser console (Firefox: Ctrl+Shift+K, Chrome: Ctrl+Shift+J)
- Paste the contents of the URL and submit

This modification first checks when content is being marked as invalid (which is logged, so keep the console open), then forces them to be marked as valid which /should/ help identify the problem.

**Comment by RePod** [comment] 2015-06-08 18:18
^

**Comment by Hyenard** [comment] 2015-06-08 18:28
Well i'm still getting 2 missing results :/

**Comment by RePod** [comment] 2015-06-08 18:28
Anything in the console?

**Comment by Hyenard** [comment] 2015-06-08 18:37
All i'm seeing is a truckload of messages regarding "SHA-1" (this must be new as i never noticed it before) and something labeled "XHR" but i couldn't manage to copy-paste them in time as they scroll down too fast.

**Comment by RePod** [comment] 2015-06-08 18:44
SHA-1 and XHR requests are store-related. I went ahead and made an actual debug command to compare the data PSDLE is using.

Please execute [this version](//gist.githubusercontent.com/RePod/a96eca1e48c1c97a2e47/raw/803ded623db8bc0a62ef542959ed57e129649e06/gistfile1.txt), as before with the Userscript disabled.

When viewing the list, in console execute: `repod.psdle.debug.difference(true)`

This will compare the two lists PSDLE uses (everything and the currently displayed items), find the differences, and force those to be displayed.

**Comment by Hyenard** [comment] 2015-06-08 19:17
I found these:

https://store.playstation.com/store/api/chihiro/00_09_000/container/IT/it/19/EP2005-PCSB00596_00-SOLDNERX2LBCROSS/image?_version=00_09_000&platform=chihiro&w=42&h=42

https://store.playstation.com/store/api/chihiro/00_09_000/container/IT/it/19/EP2005-PCSB00596_00-SOLX2LASTCHAPTER/image?_version=00_09_000&platform=chihiro&w=42&h=42

They aren't labeled as "VITA" but they're definitely the VITA versions.

**Comment by RePod** [comment] 2015-06-08 19:37
The first one is getting back this information from the Catalog:
````javascript
repod.psdle.debug.checkParse("EP2005-PCSB00596_00-SOLDNERX2LBCROSS")
Object { deep_type: "downloadable_game", rating: "4.93", images: Array[10], videos: Array[0], metadata: Object, long_desc: "Divertiti ancora di più con la vers…" }
````

The second one:
````javascript
repod.psdle.debug.checkParse("EP2005-PCSB00596_00-SOLX2LASTCHAPTER")
Object { deep_type: "add_on", rating: "4.70", metadata: Object, long_desc: "Preparati a giocare a uno sparatutt…" }
````

Notably, the second is getting a lot less information. Currently PSDLE only overwrites the determined system if it's a PS1 or PS2 classic, so if it doesn't already have that information from the Entitlements that's probably the cause (having no system associated).

----

Please execute the following code (PSDLE doesn't matter):

````javascript
$.each(gEntitlementManager.getAllEntitlements(),function(i,obj) {
    var c = (obj.drm_def||obj.entitlement_attributes)?!0:!1;
    if (c) {
        if (obj.id.indexOf("EP2005-PCSB00596_00") > -1) {
            var platform, pids = 0;
            if (obj.game_meta) { platform = ["PS4"] }
            else { 
                platform = []; pids = obj.drm_def.drmContents[0].platformIds;
                $.each({"1":KamajiPlatformFlags.PS3,"3":KamajiPlatformFlags.PSP,"8":KamajiPlatformFlags.VITA}, function (t,u) { 0 !== (pids >>> 1 & u >>> 1) && platform.push(KamajiPlatforms[Number(t)]); });
            }
            //Remove personal information (such as dates) and extraneous URLs.
            var safe = JSON.stringify(obj, function(k,v) { if(/[\d\-]+T.+Z$/.test(v) || /^http/.test(v)) { return "~" } return v; });
            console.log(i,platform,pids,safe)
        }
    }
})
````

This goes through your Entitlements, finds the problematic items (in this case "EP2005-PCSB00596_00") and logs their entitlement data. At minimum you should get two results.

**Comment by Hyenard** [comment] 2015-06-08 21:28
2744 Array [  ] 0 "{"active_date":"~","active_flag":false,"drm_def":{"active_flag":false,"autoDownload":false,"availableDate":"~","contentName":"Söldner-X 2: Final Prototype - The Last Chapter","contentType":"GAME","downloadableStatus":"ready","drmContents":[{"bitrate":0,"contentId":"EP2005-PCSB00596_00-SOLX2LASTCHAPTER","contentName":"Söldner-X 2: Final Prototype - The Last Chapter","contentSize":376743920,"contentUrl":"~","downloadType":0,"drmContentType":1,"drmType":2,"gracePeriod":0,"platformIds":0,"position":0,"spName":"eastasiasoft","titleName":"SÖLDNER-X 2: FINAL PROTOTYPE"}],"duration":0,"entitlementId":"EP2005-PCSB00596_00-SOLX2LASTCHAPTER","episodeNumber":0,"firstPlayExpiration":0,"firstPlayExpirationHours":0,"image_url":"~","media_type":0,"productId":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS","release_date":0,"runtime":0,"salesType":"own","seasonOrder":0,"startedStreaming":false,"year_release":0},"entitlement_type":2,"feature_type":0,"id":"EP2005-PCSB00596_00-SOLX2LASTCHAPTER","inactive_date":"~","is_consumable":false,"license":{"entitlement_id":"EP2005-PCSB00596_00-SOLX2LASTCHAPTER","feature_type":0,"infinite_duration":true,"start_date":"~"},"preorder_flag":false,"preorder_placeholder_flag":false,"product_id":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS","revision_id":1346355425268,"sku_id":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS-E002","subs_flag":false,"use_count":0,"use_limit":0}"




2745 Array [  ] 0 "{"active_date":"~","active_flag":false,"drm_def":{"active_flag":false,"autoDownload":false,"availableDate":"~","contentName":"Söldner-X 2: Final Prototype","contentType":"GAME","downloadableStatus":"ready","drmContents":[{"bitrate":0,"contentId":"EP2005-PCSB00596_00-SOLDNERX2FINALPR","contentName":"Söldner-X 2: Final Prototype","contentSize":950937536,"contentUrl":"~","downloadType":0,"drmContentType":1,"drmType":2,"gracePeriod":0,"platformIds":0,"position":0,"spName":"eastasiasoft","titleName":"SÖLDNER-X 2: FINAL PROTOTYPE"}],"duration":0,"entitlementId":"EP2005-PCSB00596_00-SOLDNERX2FINALPR","episodeNumber":0,"firstPlayExpiration":0,"firstPlayExpirationHours":0,"image_url":"~","media_type":0,"productId":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS","release_date":0,"runtime":0,"salesType":"own","seasonOrder":0,"startedStreaming":false,"year_release":0},"entitlement_type":2,"feature_type":0,"id":"EP2005-PCSB00596_00-SOLDNERX2FINALPR","inactive_date":"~","is_consumable":false,"license":{"entitlement_id":"EP2005-PCSB00596_00-SOLDNERX2FINALPR","feature_type":0,"infinite_duration":true,"start_date":"~"},"preorder_flag":false,"preorder_placeholder_flag":false,"product_id":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS","revision_id":1346355425268,"sku_id":"EP2005-PCSB00596_00-SOLDNERX2LBCROSS-E002","subs_flag":false,"use_count":0,"use_limit":0}"

**Comment by RePod** [comment] 2015-06-08 23:04
As expected.

Comparing with my example: `Array [ "PS3" ] 2147483648`

To your results:

- `Array [ ] 0`
- `Array [ ] 0`

The contents of the array being the determined usable systems, the number being used to determine that.

----

In short, technically PSDLE is doing the right thing by not showing them (as they have no associated systems). Enabling the Catalog could potentially overwrite (or fill in) the missing system data.

There are a few options:
- Force them to be shown even if they don't have a system (without Catalog, risky).
- Show them only if Catalog is enabled, which would appropriately assign them a system (which impacts accuracy between Catalog being enabled and disabled, also risky).
- Hide them (which I assume is intended on the actual download list).
- Continue to look into it.

Keep in mind I have to think in the grand scale, I can't just solve this specific problem without considering what else will be affected.

What I want to know is how the official Download List handles this situation. I would assume it hides them as they have no available platforms. 

If it's not too much to ask for, could I task you with checking for their appearances on the webstore's Download List and from a console? If I had to guess based on the information you provided, they should be between pages 114 and 116 (if at all).

**Comment by Hyenard** [comment] 2015-06-08 23:28
Sorry i don't have a Vita at the moment, i got the game for free through cross-buy. I bought the original and its DLC in 2012 so i was eligible.

Anyway, i found something weird: the VITA version of Soldner X 2 and its DLC are NOT on the pages you guessed. I'm checking under Account Management, and there's nothing about it on March 18, 2015 (when i got the VITA version), i went back to pages 288 and 289, and my old version's name has [Cross-Buy] added to it. And on the Download List in the Store site, the 2012 (aka PS3) files have been moved to March 18, 2015 next to the VITA one. Like i re-bought them or something...

The same applies to that Dynasty Warriors 8 Free Alliances game. I got both the PS3 and PS4 versions, but they were definitely NOT cross-buy. There's ONE entry for both versions under Account Management, and two in the list in the Store website.

**Comment by RePod** [comment] 2015-06-08 23:41
I assume when you say Account Managment you mean the one off the store and on *account.sonyentertainmentnetwork.com*? The page numbers I provided were for the store's Download List, it's fine though.

When checking under Account Management, in the second column, "Type", what does it say for those items? Looking at mine I'm seeing only **Game** and **Game Service**. If those items are **Game Service** that's probably where the issue lies.

**Comment by Hyenard** [comment] 2015-06-08 23:50
It says Game Service only for DW8, the Soldner-X 2 entries are simply Game.

Yes i mean the one off the store, sorry for the confusion.

**Comment by Hyenard** [comment] 2015-06-11 13:44
Anything new? Meanwhile i kept getting stuff and the omitted stuff is still 2-3 hopefully.

Also i wonder why certain PS3 content has no size in the PSDLE list? I know about PS4 DLC with a "N/A" size (which is blank on PSDLE) but it's weird to see it for PS3 stuff. One example is Mirror of Fate HD and its unlock key.

**Comment by RePod** [comment] 2015-06-11 17:51
>Anything new?

I've been looking into how the official Download List determines what to show.

>Also i wonder why certain PS3 content has no size in the PSDLE list?

Size is obtained from the Entitlements in raw bytes then converted.

>Do they still count to the total?

Most likely. It'd be like adding 0.

----

If you want to help with the size issue, please [use the latest version](//raw.githubusercontent.com/RePod/psdle/master/psdle.js) (run in console) which contains newer debug tools.

When ran, execute `repod.psdle.debug.entitlement("Lords of Shadow")` (replacing "Lords of Shadow" with any other problematic content).

**Comment by Hyenard** [comment] 2015-06-11 22:36
It's just that game, hopefully. I disabled the PS4 content just to be sure: http://pastebin.com/PdvUYfU7

ps: is the issue with that other game (Dynasty Warriors Free Alliances blah blah) the same as SOLDNER?

**Comment by RePod** [comment] 2015-06-11 23:19
Looking at those two entries they have a valid *platformIds* value (2147483648, PS3) but a *contentSize* value of 0. As far as PSDLE is concerned, the contentSize given is valid and cannot be determined otherwise (except for PS4 content which store their sizes elsewhere).

I went ahead and pushed this minor fix so when they have a value of 0 they're *presented* as "N/A" but still treated as 0.
![1](https://cloud.githubusercontent.com/assets/7897871/8120537/4166b330-106e-11e5-823e-d9a085df425b.jpg)
![2](https://cloud.githubusercontent.com/assets/7897871/8120538/416df2f8-106e-11e5-8c7c-e6d5039a2ad2.jpg)

>ps: is the issue with that other game (Dynasty Warriors Free Alliances blah blah) the same as SOLDNER? Or is it different because of that "Game Service" thingy?

`repod.psdle.debug.entitlement("Dynasty Warriors")` would help with that. The issue SOLDNER is having is lacking platform data (which at the moment appears to be being pulled out of thin air by the Download List).

However, I am curious on a few things:

- Are there any other SOLDNER entries already listed on PSDLE?
- Continuing from that, currently PSDLE is listing more entries than the official Download List. Perhaps this is why?

**Comment by Hyenard** [comment] 2015-06-11 23:44
Here are the results for Dynasty Warriors 8 Free Alliances (i guess the first is for the PS3 version, the one that does not appear when i don't use Catalog)

And yes, i have other Soldner entries. I have the first game, for PS3, and the second chapter with its DLC (which was bought in 2012, but the Vita cross-buy it pushed it to 2015 in the PSDLE list): http://pastebin.com/Jt1wvvRq

As you can see, five entries, but only 3 are currently visible in the PSDLE list.

**Comment by RePod** [comment] 2015-06-12 00:51
It seems the PS3 version of Dynasty Warriors has the same issue as the SOLDNER Vita items: no *platformIds* value. The PS3 version appears when using Catalog since it overwrites one of the stored platform values, but leaves the original untouched. This is best noticed if you try to open the window by clicking the item, which will fail since it still lacks proper system data.

Regardless, I added a few more debugging commands to inject Entitlements so I can work on it verbatim from my side: (Catalog enabled)

![screenshot_1](https://cloud.githubusercontent.com/assets/7897871/8121566/589db0dc-107b-11e5-8dae-7eb253f815bf.jpg)

**Comment by Hyenard** [comment] 2015-06-12 09:18
They're trailers, i have 3 of them, in two formats (PSP and PS3)

**Comment by Hyenard** [comment] 2015-06-12 13:51
Weird, now it shows only ONE missing entry, that Dynasty Warriors game, when i don't use Catalog. I guess i should get 3444 / 3444 results (what i currently have... i kept getting stuff), the two Soldner VITA entries are back.

**Comment by RePod** [comment] 2015-06-12 21:34
Given the Dynasty Warriors game had the same issue as the Soldner games (no platform data) it seems the easiest fix is to wait for it to update on Sony's side.

I'm still figuring out how it gets the system for the Download List, though. The PS3 version of Dynasty Warriors shows up on the webstore's (not Account Management) Download List, correct?

**Comment by Hyenard** [comment] 2015-06-12 21:36
Yes it shows there.

**Comment by RePod** [comment] 2015-06-13 07:25
[Using the latest version](//raw.githubusercontent.com/RePod/psdle/master/psdle.js) (run in console) again, please execute `repod.psdle.debug.entitlement("EP2005-","id")` which should log all the SOLDNER items' Entitlement data.

I have a feeling the Entitlements were updated (aside from the now existing platform data), and should at least reflect the change and maybe other differences.

**Comment by Hyenard** [comment] 2015-06-13 17:56
http://pastebin.com/Nv4gxpga

Please ignore the Rainbow Moon / Beginner's Kit entries

**Comment by RePod** [comment] 2015-06-13 18:51
As I suspected. At some point the Vita entries for SOLDER were updated, as shown by the them getting platform data, but also from their *revision_id* attribute changing:

- Before: `1346355425268` (2012-08-30T19:37:05.268Z)
- After: `1346355426706` (2012-08-30T19:37:06.706Z)

Assuming the dates are irrelevant, during the course of finding out the issue their data was modified from Sony's side (and probably somewhere around the point you viewed them on the Download List). I want to say the PS3 version of Dynasty Warriors is in the same situation, but I'll continue to look into it.

**Comment by Hyenard** [comment] 2015-06-16 13:34
I have another question: do you think it's possible to implement an item counter for the Download Queue just like official one? And a way to add multiple items at once? I'm redownloading everything due to a bad HDD management and it's a PITA to click items one by one. With a limit of 100 items and 32 simultaneous downloads every time.

**Comment by RePod** [comment] 2015-06-16 17:01
>The problem with Dynasty Warriors has been fixed, and you didn't have to do anything, lol. 

Welp! I can finally push all these later changes live I guess.

>do you think it's possible to implement an item counter for the Download Queue just like official one?

If you mean viewable from the list (the Queue button), it's definitely possible. PSDLE's Download Queue needs a lot of improvement to begin with, this is definitely on the list.

>And a way to add multiple items at once?

Fun fact: originally PSDLE sent item in batches (when I first implemented Queue support).

However, at that time I was only sending items to PS3 so I didn't have to worry about the platforms. As soon as I find out a decent solution to handle multi-platform items (auto handle, send to one, ignore, etc.) as well as selecting all the desired items, batch support will be available.

**Closed** 2015-06-16 17:04 UTC

**Comment by Hyenard** [comment] 2015-06-16 18:07
I see, thank you. Until next time.
