### ISSUE TITLE
[API Change] Chihiro -> Valkyrie cause PSDLE to not work anymore

### ISSUE THREAD

**Issue by juliosueiras** [RePod/psdle#40] opened 2017-11-08 02:45 UTC
## Description:

Due to recent API shift of PSS , PSDLE won't launch due missing function(again due to api changes)

## Screentshot:

<img width="1280" alt="screen shot 2017-11-07 at 9 35 49 pm" src="https://user-images.githubusercontent.com/3680302/32528948-ae5b22d2-c403-11e7-950b-559ef530c1df.png">

## Workaround for now:
The access to internal_entitlements is still there, if someone want to get pkg or other info of what they purchase

```
'https://commerce.api.np.km.playstation.net/commerce/api/v1/users/me/internal_entitlements?meta_rev=0&revision=0&start=0&size=<max_item>&fields=meta_rev%2Ccloud_meta%2Creward_meta%2Cgame_meta%2Cdrm_def%2Cdrm_def.content_type'

with a header of  'authorization: Bearer <bearer token>'
```

bearer token can be grab by going to pss

**Comment by RePod** [comment] 2017-11-08 17:24
Currently broken:
 - Catalog (URL needs to be determined)
 - DL Queue (several URLs need to be determined)
 - CSS
 - Tooltips and Autocomplete (no jQuery UI)
 - Locale date formatting
 - PS+ toggling (should be an easy fix)

---

**Problem:** Seeing more games than are on account/not on account.
**Solution:** Ignore it or run `localStorage.clear()` in console. Caused by using multiple accounts on the store.

**Comment by RePod** [comment] 2017-11-15 18:37
PSDLE should now be near fully operational as it was on Chihiro. There's a few edge-cases left but for most users all other cases should be covered. No need to close the issue though, as this is ongoing.

If you could test and report back for anything newly broken or not functioning as expected, that'd be great. All available versions (direct, userscript, etc) are up to date for testing.

**Comment by RePod** [comment] 2017-11-21 00:07
PSDLE currently performs a workaround for obtaining entitlements, as the store has a problem if it cannot fit them all into `localStorage`.

The workaround pulls the entitlements directly from `s:MB.macrossBrainInstance._entitlementStore._storage._entitlementMapCache` and processes them as they've always been.

In the future, if the issue is resolved in Valkyrie, it would be preferable to do something like `s:MB.macrossBrainInstance.getEntitlementStore().getAllEntitlements().then()` or `s:MB.macrossBrainInstance.getEntitlementStore() -> .sync().then()`.

**Comment by RePod** [comment] 2017-11-26 23:06
Almost everything is back in working order, barring PS TV and deleting from the download queue.

I'm going to consider this issue resolved on the surface, but there is going to be an on-going effort to keep improving edge cases and restore temporarily disabled functionality.

Any additional feedback should be directed to #43

**Closed by RePod** 2017-11-26 23:06 UTC
